/* Source and licensing information for the line(s) below can be found at http://localhost:8888/48specials/core/modules/editor/js/editor.dialog.js. */
(function(o,i){i.AjaxCommands.prototype.editorDialogSave=function(e,i,a){o(window).trigger('editor:dialogsave',[i.values])}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at http://localhost:8888/48specials/core/modules/editor/js/editor.dialog.js. */;
/* Source and licensing information for the line(s) below can be found at http://localhost:8888/48specials/modules/linkit/js/linkit.js. */
(function(u,t,i){'use strict';t.linkit={}})(jQuery,Drupal,drupalSettings);
/* Source and licensing information for the above line(s) can be found at http://localhost:8888/48specials/modules/linkit/js/linkit.js. */;
/* Source and licensing information for the line(s) below can be found at http://localhost:8888/48specials/modules/linkit/js/autocomplete.js. */
(function(t,n,i,a){'use strict';var e;function o(n,i){var a=this.element.attr('id');if(!(a in e.cache)){e.cache[a]={}};function r(t){i(t.matches)};function u(t){e.cache[a][o]=t;r(t)};var o=n.term;if(e.cache[a].hasOwnProperty(o)){r(e.cache[a][o])}
else{var c=t.extend({success:u,data:{q:o}},e.ajax);t.ajax(this.element.attr('data-autocomplete-path'),c)}};function r(e,n){if(n.item.hasOwnProperty('path')){e.target.value=n.item.path};t(a).trigger('linkit.autocomplete.select',[e,n]);return!1};function c(e,n){var i=t('<li>').addClass('linkit-result');i.append(t('<span>').html(n.title).addClass('linkit-result--title'));if(n.description!==null){i.append(t('<span>').html(n.description).addClass('linkit-result--description'))};return i.appendTo(e)};function u(e,n){var a=this.element.autocomplete('instance'),o=i.groupBy(n,function(t){return t.hasOwnProperty('group')?t.group:''});t.each(o,function(n,i){if(n.length){e.append('<li class="linkit-result--group">'+n+'</li>')};t.each(i,function(t,n){a._renderItemData(e,n)})})};n.behaviors.linkit_autocomplete={attach:function(n){var i=t(n).find('input.form-linkit-autocomplete').once('linkit-autocomplete');if(i.length){t.widget('custom.autocomplete',t.ui.autocomplete,{_create:function(){this._super();this.widget().menu('option','items','> :not(.linkit-result--group)')},_renderMenu:e.options.renderMenu,_renderItem:e.options.renderItem});i.autocomplete(e.options);i.autocomplete('widget').addClass('linkit-ui-autocomplete')}},detach:function(e,n,i){if(i==='unload'){t(e).find('input.form-linkit-autocomplete').removeOnce('linkit-autocomplete').autocomplete('destroy')}}};e={cache:{},options:{source:o,renderItem:c,renderMenu:u,select:r,minLength:1},ajax:{dataType:'json'}}})(jQuery,Drupal,_,document);
/* Source and licensing information for the above line(s) can be found at http://localhost:8888/48specials/modules/linkit/js/autocomplete.js. */;
